In [1]:
import numpy as np

## 1. Data Types & Attributes

In [2]:
# NumPy's main datatype is ndarray (n-dimensional array)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0,3.3], [4,5,6.5]])
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [17]:
sample_array = np.array([1,3,4])
sample_array

array([1, 3, 4])

In [18]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size = (3,5))
random_array

array([[2, 2, 1, 7, 5],
       [9, 9, 1, 9, 1],
       [1, 4, 0, 4, 7]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [28]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.90376642, 0.38307217, 0.49756969],
       [0.85296296, 0.7094162 , 0.85343872],
       [0.28781025, 0.19100121, 0.35639112],
       [0.11752462, 0.7678128 , 0.63621688],
       [0.74002807, 0.01805266, 0.09611262]])

In [29]:
random_array_2.shape

(5, 3)

In [30]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.70804199, 0.22416003, 0.51680728],
       [0.14983512, 0.64988033, 0.24247573],
       [0.19625341, 0.30989968, 0.3539814 ],
       [0.39282334, 0.50524273, 0.96491715],
       [0.0094519 , 0.27588431, 0.16922273]])

In [33]:
random_array_4.shape

(5, 3)

In [35]:
#Pseudo-random Numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [43]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [44]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## 3. Viewing arrays and matrices

In [46]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a1[0]

1

In [48]:
a2[0]

array([1. , 2. , 3.3])

In [49]:
a3.shape

(2, 3, 3)

In [50]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a2[1]

array([4. , 5. , 6.5])

In [52]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [53]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [55]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [72]:
# Get the first 4 numbers of the inner most array
a4[:,:,:,:4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

## 4. Manipulating & Comparing Arrays

### Arithmetic

In [73]:
a1

array([1, 2, 3])

In [75]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [76]:
a1 + ones

array([2., 3., 4.])

In [77]:
a1 - ones

array([0., 1., 2.])

In [78]:
a1 * ones

array([1., 2., 3.])

In [79]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [80]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [81]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [83]:
a1 / ones

array([1., 2., 3.])

In [84]:
# Floor division - removes decimal (round down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [85]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [86]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [87]:
np.add(a1, ones)

array([2., 3., 4.])

In [88]:
np.mod(a2, ones)

array([[0. , 0. , 0.3],
       [0. , 0. , 0.5]])

In [89]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [90]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things

In [93]:
list1 = [1,2,3]
type(list1)

list

In [94]:
sum(list1)

6

In [95]:
a1

array([1, 2, 3])

In [96]:
sum(a1)

6

In [97]:
np.sum(a1)

6

#### Use Python's methods (`sum()`) on Python datatypes & use NumPy's methods on NumPy arrays (`np.sum()`)

In [98]:
# Create NumPy array
massive_arr = np.random.random(100000)
massive_arr.size

100000

In [99]:
massive_arr[:10]

array([0.62342345, 0.62955693, 0.9099729 , 0.96251949, 0.5850998 ,
       0.16489774, 0.39159332, 0.94455493, 0.34339118, 0.70507037])

In [102]:
%timeit sum(massive_arr) # Python's sum() timed
%timeit np.sum(massive_arr) #NumPy's sum() timed

4.57 ms ± 87.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
20.3 μs ± 279 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [103]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [104]:
np.mean(a2)

3.6333333333333333

In [111]:
# Standard Deviation = A measure of the spread or dispersion of a set of numbers. It is the square root of the variance and is expressed in the same units as the data.
# Square root of the Variance
np.max(a2), np.mean(a2), np.std(a2)

(6.5, 3.6333333333333333, 1.8226964152656422)

In [112]:
# Variance = A measure of how much each number in a dataset differs from the mean of the dataset, on average. It is calculated as the average of the squared differences from the mean.
# Higher variance = wider range of numbers
np.var(a2)

3.3222222222222224

In [113]:
np.sqrt(np.var(a2))

1.8226964152656422